name: commit

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: agenthunt/conventional-commit-checker-action@v1.0.0
