name: Commit Lint

on: [push, pull_request]

jobs:
  pre_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit_message
        run: echo ::set-output name=commit_message::$(git log --format=%B -n 1)

    outputs:
      commit_message: $( echo "${{ steps.commit_message.outputs.commit_message }}" )

  commitlint:
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn ci
      - run: echo "${{ needs.pre_ci.outputs.commit_message }}" >> COMMIT_MESSAGE
      - run: yarn commitlint --edit COMMIT_MESSAGE