name: deploy-athena

on:
  workflow_dispatch:
  push:
    branches: [production]
    paths:
      - athena/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: cd athena
      - run: npm install
      - run: npm run build
      - run: tar -cvzf build.tar.gz dist

      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production - athena
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: builds

      - run: tar -xvf build.tar.gz

      - uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: ./dist
          production-branch: production
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: Deploy from GitHub Actions
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
