name: pr-test-athena

on:
  pull_request:
    branches: [main]
    paths:
      - athena/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: cd athena
      - run: npm install
      - run: npm run build
