name: pr-test-xanatha

on:
  pull_request:
    branches: [main]
    paths:
      - xanatha/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: ./xanatha
        run: |
          npm ci
          npm run build
