name: pr-test-xanatha

on:
  pull_request:
    branches: [main]
    paths:
      - scripts/bootstrap.sh
      - tsconfig.json
      - xanatha/**
      - shared/database/**
      - shared/env/**
      - shared/types/**
      - scripts/xanatha/**
  
jobs:
  pre_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit_message
        run: echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD^2)

    outputs:
      commit_message: $( echo "${{ steps.commit_message.outputs.commit_message }}" )

  test:
    needs: pre_ci
    runs-on: ubuntu-latest
    if: "!contains(needs.pre_ci.outputs.commit_message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Bootstrap
        run: yarn bootstrap

      - name: Build
        run: yarn build:xanatha
