name: test-athena

on:
  push:
    branches: [main]
    paths:
      - athena/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging - athena
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: ./athena
        run: |
          npm ci
          npm run build
