name: Staging - xanatha

on:
  push:
    branches: [main]
    paths:
      - scripts/bootstrap.sh
      - config/tsconfig.eslint.json
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - xanatha/**
      - shared/database/**
      - shared/env/**
      - shared/types/**
      - .github/workflows/test-xanatha.yml
      - scripts/xanatha/**

jobs:
  pre_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit_message
        run: echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)

    outputs:
      commit_message: $( echo "${{ steps.commit_message.outputs.commit_message }}" )

  lint:
    needs: pre_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn

      - name: Lint
        run: yarn lint:xanatha

  test:
    needs: pre_ci
    runs-on: ubuntu-latest
    environment: Staging - xanatha
    if: "(!contains(needs.pre_ci.outputs.commit_message, '[skip test]')  && !contains(needs.pre_ci.outputs.commit_message, 'chore(release): publish'))"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn

      - name: Build
        run: yarn build:xanatha
