name: test-xanatha

on:
  push:
    branches: [main]
    paths:
      - xanatha/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging - xanatha
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - working-directory: ./xanatha
        run: |
          npm ci
          npm run build
