name: Staging - cathy

on:
  push:
    branches: [main]
    paths:
      - scripts/bootstrap.sh
      - tsconfig.json
      - cathy/**
      - shared/**
      - .github/workflows/test-cathy.yml
      - scripts/cathy/**

jobs:
  pre_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit_message
        run: echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)

    outputs:
      commit_message: $( echo "${{ steps.commit_message.outputs.commit_message }}" )

  lint:
    needs: pre_ci
    runs-on: ubuntu-latest
    if: "(!contains(needs.pre_ci.outputs.commit_message, '[skip ci]') && !contains(needs.pre_ci.outputs.commit_message, 'chore(release): publish'))"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        id: cache-restore
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint:cathy

  test:
    needs: pre_ci
    runs-on: ubuntu-latest
    environment: Staging - cathy
    if: "(!contains(needs.pre_ci.outputs.commit_message, '[skip ci]') && !contains(needs.pre_ci.outputs.commit_message, 'chore(release): publish'))"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        id: cache-restore
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile

      - name: Bootstrap
        run: yarn bootstrap

      - name: Build
        run: yarn build:cathy
