name: xanatha-test

on:
  push:
    branches: [main]
    paths:
     - /xanatha/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging - xanatha
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: cd xanatha
      - run: npm install
      - run: npm run build